import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import UserSync from '@/components/final/UserSync'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { ReactQueryProvider } from './react-query-provider'

export const metadata = {
  title: 'Plutus',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <UserSync />
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                {children}
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
